[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/shrimp-software/eoka-tools"
homepage = "https://github.com/shrimp-software/eoka-tools"
authors = ["cbxss"]

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive", "env"] }
schemars = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tack-core = { version = "0.0.2", features = ["schemars"] }
tack-runtime-quickjs = "0.0.2"
tokio = { version = "1", features = ["full"] }
