[package]
name = "eoka-cli"
version = "0.1.10"
edition = "2021"
license = "MIT"
description = "Browser automation CLI for AI agents and pentesting"
repository = "https://github.com/shrimp-software/eoka-tools"
authors = ["cbxss"]

[[bin]]
name = "eoka"
path = "src/main.rs"

[dependencies]
eoka-mcp = { version = "0.1.0", path = "../eoka-mcp" }
eoka-proxy = { path = "../eoka-proxy", version = "0.1.0" }
captcha = { package = "eoka-captcha", version = "0.1.1", path = "../captcha" }
eoka = "0.5"
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
base64 = "0.22"
anyhow = { workspace = true }
url = "2"
